// SafeCampus AI — Fallback Campus Data (Offline & No-Network Resilience)
import '../../models/campus_location.dart';

abstract class FallbackCampusData {
  static const List<CampusLocation> locations = [
    CampusLocation(
      id: 1,
      name: "Main Gate",
      latitude: 12.9716,
      longitude: 77.5946,
      locationType: "gate",
      description: "Primary campus entrance",
    ),
    CampusLocation(
      id: 2,
      name: "Admin Block",
      latitude: 12.9720,
      longitude: 77.5950,
      locationType: "building",
      description: "Administrative offices and principal's office",
    ),
    CampusLocation(
      id: 3,
      name: "Junction A",
      latitude: 12.9724,
      longitude: 77.5948,
      locationType: "junction",
      description: "Central pathway junction near Admin",
    ),
    CampusLocation(
      id: 4,
      name: "CSE Block",
      latitude: 12.9730,
      longitude: 77.5942,
      locationType: "building",
      description: "Computer Science and Engineering department",
    ),
    CampusLocation(
      id: 5,
      name: "ECE Block",
      latitude: 12.9730,
      longitude: 77.5955,
      locationType: "building",
      description: "Electronics and Communication Engineering department",
    ),
    CampusLocation(
      id: 6,
      name: "Junction B",
      latitude: 12.9728,
      longitude: 77.5948,
      locationType: "junction",
      description: "North pathway junction between CSE and ECE",
    ),
    CampusLocation(
      id: 7,
      name: "Library",
      latitude: 12.9735,
      longitude: 77.5948,
      locationType: "library",
      description: "Central library with reading halls",
    ),
    CampusLocation(
      id: 8,
      name: "Canteen",
      latitude: 12.9722,
      longitude: 77.5956,
      locationType: "canteen",
      description: "Campus cafeteria and food court",
    ),
    CampusLocation(
      id: 9,
      name: "Mechanical Block",
      latitude: 12.9736,
      longitude: 77.5938,
      locationType: "building",
      description: "Mechanical engineering labs and workshops",
    ),
    CampusLocation(
      id: 10,
      name: "Civil Block",
      latitude: 12.9736,
      longitude: 77.5958,
      locationType: "building",
      description: "Civil engineering block and survey lab",
    ),
    CampusLocation(
      id: 11,
      name: "Auditorium",
      latitude: 12.9718,
      longitude: 77.5940,
      locationType: "auditorium",
      description: "Main event auditorium and cultural center",
    ),
    CampusLocation(
      id: 12,
      name: "Sports Complex",
      latitude: 12.9740,
      longitude: 77.5944,
      locationType: "sports",
      description: "Indoor sports arena and gym",
    ),
    CampusLocation(
      id: 13,
      name: "Boys Hostel",
      latitude: 12.9742,
      longitude: 77.5935,
      locationType: "hostel",
      description: "Men's student residence hall",
    ),
    CampusLocation(
      id: 14,
      name: "Girls Hostel",
      latitude: 12.9742,
      longitude: 77.5960,
      locationType: "hostel",
      description: "Women's student residence hall",
    ),
    CampusLocation(
      id: 15,
      name: "Health Center",
      latitude: 12.9715,
      longitude: 77.5955,
      locationType: "medical",
      description: "First-aid clinic and ambulance bay",
    ),
    CampusLocation(
      id: 16,
      name: "Parking Area",
      latitude: 12.9712,
      longitude: 77.5944,
      locationType: "parking",
      description: "Two-wheeler and four-wheeler campus parking",
    ),
    CampusLocation(
      id: 17,
      name: "Innovation Lab",
      latitude: 12.9732,
      longitude: 77.5940,
      locationType: "building",
      description: "AI & robotics incubation centre",
    ),
    CampusLocation(
      id: 18,
      name: "Junction C",
      latitude: 12.9738,
      longitude: 77.5948,
      locationType: "junction",
      description: "North campus intersection near Sports Complex",
    ),
    CampusLocation(
      id: 19,
      name: "East Gate",
      latitude: 12.9725,
      longitude: 77.5965,
      locationType: "gate",
      description: "Secondary pedestrian exit towards transit station",
    ),
    CampusLocation(
      id: 20,
      name: "West Gate",
      latitude: 12.9725,
      longitude: 77.5932,
      locationType: "gate",
      description: "Service and emergency vehicle entrance",
    ),
  ];

  // Campus path edges (node ID pairs) for offline schematic graph visualization
  static const List<List<int>> edges = [
    [1, 16],
    [1, 2],
    [1, 15],
    [2, 3],
    [2, 15],
    [2, 8],
    [3, 4],
    [3, 6],
    [3, 11],
    [4, 6],
    [4, 9],
    [4, 17],
    [4, 20],
    [5, 6],
    [5, 8],
    [5, 10],
    [5, 19],
    [6, 7],
    [7, 8],
    [7, 18],
    [8, 19],
    [9, 13],
    [9, 17],
    [9, 20],
    [10, 14],
    [10, 19],
    [11, 16],
    [11, 20],
    [12, 13],
    [12, 18],
    [12, 14],
    [13, 18],
    [14, 18],
    [15, 19],
    [17, 18],
  ];
}
