include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unused_import: error
    unused_local_variable: warning
  exclude:
    - build/**
    - android/**
    - web/**
    - windows/**
